# 配置文件加密key 生产环境中可通过环境变量、命令行等形式进行设置
jasypt:
  encryptor:
    password: leiyanfu   # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为  ENC(加密结果)

server:
  port: 8888
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    # 最大吞吐量不限制
    max-swallow-size: -1
  # 优雅停机 关闭容器后默认等待30秒继续执行没处理完的任务 避免数据不一致
  shutdown: graceful

spring:
  lifecycle:
    # 配置优雅停机后的缓冲器 最大等待时间
    timeout-per-shutdown-phase: 10S
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRestClientAutoConfiguration
  # 数据源
  datasource:
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: root
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
      filter:
        stat:
          # 开启监控sql
          enabled: true
          # 显示并标注慢sql 默认当超过3秒显示
          log-slow-sql: true
          slow-sql-millis: 3000
          merge-sql: true
        # 防SQL注入过滤
        wall:
          config:
            # 允许多条sql同时执行
            multi-statement-allow: true
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          url: jdbc:mysql://cc.c0c0.cc:3306/legion?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password:
          driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    #   password: leiyanfu
    # 数据库索引 默认0
    database: 1
    port: 6379
    # 超时时间 Duration类型 3秒
    timeout: 3S

  jpa:
    # 显示sql
    show-sql: true
    # 自动生成表结构 关闭设为  none create
    hibernate:
      ddl-auto: none
  # Elasticsearch
  data:
    elasticsearch:
      # 暂未使用ES 关闭其持久化存储
      repositories:
        enabled: false
  elasticsearch:
    rest:
      # 要连接的ES客户端Rest Uri 多个逗号分隔
      uris: http://localhost:9200
  # 定时任务
  quartz:
    # 任务信息存储至数据库
    job-store-type: jdbc
    jdbc:
      # 自动生成表 若已有表数据请务必关闭 ALWAYS/EMBEDDED/NEVER
      initialize-schema: NEVER
    properties:
      org:
        quartz:
          scheduler:
            # 允许调度程序节点一次获取（触发）的最大触发器数
            batchTriggerAcquisitionMaxCount: 5
          jobStore:
            # 加锁调度
            acquireTriggersWithinLock: true
            # “容忍”触发器经过下一次触发时间的毫秒数
            misfireThreshold: 10000
  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jackson:
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
  boot:
    admin:
      # 修改上下文路径
      context-path: /admin
      client:
        # 服务端url
        url: http://127.0.0.1:${server.port}/admin
        instance:
          # 实例url
          service-base-url: http://127.0.0.1:${server.port}/
  web:
    resources:
      cache:
        cachecontrol:
          # 静态资源缓存30天
          max-age: 30D

legion:
  # 全局限流
  ratelimit:
    # 开启
    enable: true
    # 每1秒内（单位毫秒）
    timeout: 1000
    # 总限制200个请求（单位个）
    limit: 200
  # IP限流
  iplimit:
    # 开启
    enable: true
    # 每1秒内（单位毫秒）
    timeout: 1000
    # 每个ip限制20个请求（单位个）
    limit: 20
  # 后台token交互方式
  token:
    # 默认为true，token将存入redis，并具有单设备登录、自动刷新token过期时间功能 设为false使用JWT交互
    redis: true
    # 是否开启单设备登陆 一个账号仅支持同时一台设备登录 仅当token交互方式为redis时生效
    sdl: false
    # token中存储用户权限数据 开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
    storePerms: true
    # token过期时间 redis模式有请求自动刷新过期时间（分钟）
    tokenExpireTime: 60
    # 用户选择 保存登录状态/记住我 对应token过期时间 不会自动刷新过期时间（天）
    saveLoginTime: 7
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 10
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 10
  # app应用 token交互配置
  appToken:
    # 是否开启同一平台单设备登陆（如安卓设备只允许登录一个相同账号，IOS设备可允许一个设备同时登陆）
    spl: true
    # token过期时间 有请求自动刷新（天）
    tokenExpireTime: 30
  # 使用Spring @Cacheable注解失效时间
  cache:
    # 缓存过期时间 Duration类型 D–天 H小时 M–分钟 S–秒 永久不过期设为非正值
    timeToLive: 15D
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: false
  # 文件大小上传配置 单位MB
  maxUploadFile: 5
  # 腾讯位置服务key配置 腾讯位置服务官网注册添加key
  qqlbs:
    key: 7QPBZ-5TXKO-HADWR-SSJ5R-F5HIE-FJFN6
  # 第三方社交登录配置
  social:
    # 前端回调登录地址
    callbackFeUrl: http://127.0.0.1:9999/login
    # 前端绑定账号回调地址
    callbackFeRelateUrl: http://127.0.0.1:9999/relate
    # github
    github:
      clientId: 8fa14bd32a0f73c74627
      clientSecret: cbd204bf8f390af6ee5bb1fa4b051e0275334f22
      callbackUrl: http://escort.esmooc.com/api/social/github/callback
    # qq
    qq:
      appId: 101953791
      appKey: a8a54f76ffd94552cd8388dee3e933d4
      callbackUrl: http://escort.esmooc.com/api/social/qq/callback
    # weibo
    weibo:
      appKey: 1974961732
      appSecret: 89a4a4ae675cec8f76e0244a8002d349
      callbackUrl: http://escort.esmooc.com/api/social/weibo/callback
    # wechat
    wechat:
      appId: 你的appId
      appSecret: 你的appSecret
      callbackUrl: http://escort.esmooc.com/api/social/wechat/callback
    # 钉钉
    dingding:
      # 扫码登录应用
      appId: dingoaswmfaffvk7w2jwi9
      appSecret: I67-1um9wYQRI8In3yY6x-9MPGnAOAWYV48R9WpfLaUJjKt5UYqMuAE3FrNFsYJr
      callbackUrl: http://escort.esmooc.com/api/social/dingding/callback
    # 企业微信
    workwechat:
      appId: 你的appId 企业的CorpID
      agentId: 你的应用ID
      appSecret: 你的应用Secret
      callbackUrl: http://escort.esmooc.com/api/social/workwechat/callback
    # 小程序
    smallprogram:
      appid: wx5f28339f5302b65e
      secret: 26987873ecc97d58f34959d9567161a9
      granttype: authorization_code
      callbackUrl: http://escort.esmooc.com/api/social/workwechat/callback

# 需要验证码校验的接口路径 支持通配符 自动过滤拦截校验 无需开发人员再次校验
captcha:
  # 图片验证码验证
  image:
    - /legion/login # 登录接口
    - /legion/oauth2/authorize # 认证接口
  # 短信验证码验证
  sms:
    - /legion/user/regist # 注册接口
    - /legion/user/smsLogin # 短信登录接口
    - /legion/user/resetByMobile # 手机重置密码
    - /legion/user/changeMobile # 更换绑定手机
    - /legion/app/v1/member/quickLogin # 会员快捷登录注册接口
  # Vaptcha验证码验证
  vaptcha:
    - /legion/common/captcha/sendRegistSms/** # 发送注册短信
    - /legion/common/captcha/sendResetSms/** # 发送重置密码短信
    - /legion/email/sendResetCode/** # 发送重置密码邮件
    - /legion/social/relate # 绑定第三方账号
  email:
    - /legion/email/resetByEmail # 邮件重置密码
    - /legion/email/editEmail # 修改绑定邮箱

# 忽略url
ignored:
  # 无需登录认证的请求
  urls:
    - /legion/oauth2/**
    - /legion/actuator/**
    - /legion/admin/**
    - /legion/chat/**
    - /legion/dictData/getByType/**
    - /legion/email/sendResetCode/**
    - /legion/email/resetByEmail
    - /legion/file/view/**
    - /legion/social/**
    - /legion/ws/**
    - /legion/setting/notice
    - /legion/user/regist
    - /legion/user/smsLogin
    - /legion/user/resetByMobile
    - /legion/common/**
    - /druid/**
    - /doc.html
    - /swagger-ui.html
    - /swagger-resources/**
    - /v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /test/**
  # 限流及黑名单不拦截的路径
  limitUrls:
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico


# 接口文档增强UI Swagger界面内容配置
knife4j:
  enable: true



# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
  #  这个是干嘛的
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: del_flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# 日志
logging:
  # 输出级别
  level:
    root: info
  file:
    # 指定路径
    path: legion-logs
  logback:
    rollingpolicy:
      # 最大保存天数
      max-history: 7
      # 每个文件最大大小
      max-file-size: 5MB